### ISSUE TITLE
Need to know various Input Field Sectections

### ISSUE THREAD

**Issue by kevinpostal** [appliedmerchantsystems/appliedmerchantsystems.github.io#5]
Need to know the options for the different drop down selectors. 

![screen shot 2016-03-01 at 12 00 00 pm](https://cloud.githubusercontent.com/assets/157747/13440077/273e6a3c-dfa5-11e5-918e-c974731f30ed.png)

**Comment by kevinpostal** [comment]
Right now Just options for Business Structure.

**Comment by appliedmerchant** [comment]
![2016-03-01_16-13-27](https://cloud.githubusercontent.com/assets/16888864/13446478/c81acffe-dfc8-11e5-9f5b-e77cc3ffa445.png)

**Comment by kevinpostal** [comment]
@appliedmerchant  Added
